Development (#9)
* change firebase credentials to dev

* delete console

* remove json parse

* change name to firebase credentials

* add json parse to firebase credentials

* delete json parse

* add json parse

* add console log

* add base path to search img and favicon

* delete /

* delete /

* url without basepath

* fix search bar: now shows the correct month and destination and updates to ALL if destination changes. Add search for month and destination different than ALL

* add search for specific destination - ALL months and specific month and ALL destinations

* add destination page. TODO: SWLWRAPPER to images

* open new tab when click on Buscar

* update head title for each page

* add NEXT_PUBLIC_BASE_PATH to search-img

* fix days/nights in destination page

* add whatsapp button

* add hover to whatsapp button

* check if destinations have data. Add Default image in destination content

* check if boarding includes mar del plata y zona and change text_boarding in base of that

* add list_boarding to show/hide + in sidebar. Add margin in mobile for search bar. Add dolar currency

* in search page: when it doesnt have images, when you click it appears the modal so they can do the consult right there. Add provider to mail consult. Add notification provider to search page

* fix lowerCase in destination and month differnt than ALL. Add conditional ternary to img_default and search_img

* fix img_default with process.env

* add notification for all the pages

* change margin left to first destination image in destination page

* add ... to selected options in searchbar

* add description to MediumCard. If it is wave, it completes with departures. If it is ceara, it completes with sheet

* fix error: a.lowercase is not a function when sorting months for description of mediumcard

* fix ordenar by in serach. It was rerendering the page when pclick on Mostrar mas

* update: order by asc and desc USD and pesos

* add promotions values as a variable

* add promotion to destination page

* add 404 page and check if destinationId exists, if not redirect to 404

* add getAuth to firebase connection

* add destinations related to destination page. Fix: dont show promotions if they dont exist

* add SRLWRAPPER to images in destination page.

* fix undefined of destinationImages. Add space top in destination related.

* fix undefined destinationImages[title] and img_res.length

* add imp to mediumCard and sidebar

* remove no info disponible if there are no images and description for destination page

* update remove-selection

* add text shadow to destination page title

* when click in mediumCard update views in firestore. Order by views in fetchalldestinations. Add order by populares in dropdown in search page

* add home, buscar y contacto in header. fix: remove undefined from imgsDest

* remove useEffect for images. That information is now in the fetch for destinations

* add whatsapp to contact

* fix: search all all now checks if destinations names array contains the destination that was searched.

* update: fetchDestRelated: orderby views. avoid the destination that is selected and show the destinations related on the months that contains

* add lightbox to see the images full screen in destination page when you click on an image

* add cache for firestore requests

* low the re-renders

* change url_whatsapp constant

* add condition to update data from server

* order by promotions and views for popular destinations and destinos destacados

* delete + in url_whatsapp. change padding in search bar for mobile: bigger

* add destinations related always show 3 elements

* add head to destination content

* fix unsufficient permissions first time it's renders when dont have cache. Fix: hours to refill data and the query once it takes the data from the server

* add import query

* fix images/path in next.config.js: add space

* add github action to external repo

* change zindex in mediumCard. So it can be shown the promotions

* refactor refillDataFirestore and change text about us

* searchbar: you can write and search for a destination (it filters the information). Create constants for text in the page

* change size for slide-title and slide-text carousel

* update sizes on slide-text-destination

* center button mostrar mas. Close modal is now bigger

* hide arrows from carosuel if leng of images is lower than 2. Add env variable for mailROUTE

* add days in email consult. Change turismo serrano for sobre nosotros in about us. add tapeables in address/number/email

* update email link

* change base path for turismoSerrano

* delete basepath for production.yml

* add staging yml. For prod: we have to push on branch turismo-serrano